import turtle
#t1=turtle.getscreen()
turtle.up()
turtle.color('brown')
turtle.fillcolor('brown')
turtle.setpos(-200,100)
turtle.down()
turtle.right(90)
turtle.begin_fill()
#semi circle
turtle.circle(200, 180)
turtle.left(90)
turtle.forward(400)
turtle.end_fill()
#turlte.up()
turtle.color('black')
turtle.back(200)
turtle.right(90)
turtle.down()
turtle.forward(50)
turtle.right(90)
#turtle.forward(50)
turtle.up() 
turtle.color("#e6e854")  #color picker
turtle.fillcolor("#e6e854")
turtle.begin_fill()
turtle.setpos(-50,200)
turtle.right(90)
turtle.down()
turtle.circle(50,180)
turtle.left(30)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.end_fill()
turtle.up()
turtle.setpos(-250,-200)
turtle.color('#54e865')
turtle.write("HAPPY DIWALI", font=("Lucidal Calligraphy", 55))
turtle.hideturtle()
turtle.exitonclick()

  