import turtle
t = turtle.Turtle()
s = turtle.Screen()
s.bgcolor('black')
t.color('red')
t.begin_fill()
t.pensize(4)
t.left(50)
t.forward(133)
t.circle(50,200)
t.right(140)
t.circle(50,200)
t.forward(133)
t.end_fill()
t.up()
t.setpos(-200,-200)
t.color("#ff0000")
#new_update 
t.write("Love to Code 😍😍", font=("Lucidal Calligraphy", 40))
t.getscreen()._root.mainloop()